name: cafe-literario
recipe: wordpress
config:
  webroot: web
  php: "8.2"
  via: nginx
  xdebug: false
  database: mariadb:10.6

proxy:
  appserver_nginx:
    - cafe-literario.lndo.site
  node:
    - localhost:3000
    - localhost:3001

services:
  node:
    type: node:20
    overrides:
      ports:
        - 3000:3000
        - 3001:3001

tooling:
  wp:
    service: appserver
    cmd: wp
  composer:
    service: appserver
    cmd: composer
  yarn:
    service: node
    cmd: yarn
    dir: /app/web/app/themes/inter-alia
  npm:
    service: node
    cmd: npm
    dir: /app/web/app/themes/inter-alia
  cache-clear:
    service: appserver
    description: Limpa todos os caches do projeto (WordPress, tema, Composer, PHP)
    dir: /app
    cmd: bash .lando/scripts/cache-clear.sh
  cc:
    service: appserver
    description: Alias para cache-clear - Limpa todos os caches do projeto
    dir: /app
    cmd: bash .lando/scripts/cache-clear.sh
